### ISSUE TITLE
backdate function

### ISSUE THREAD

**Issue by brucewzj99** [brucewzj99/tele-tracker-v2#24]
**Is your feature request related to a problem? Please describe.**
To allow adding of backlog, as adding manually on google sheet requires the edit of the tracking sheet which can be confusing

**Describe the solution you'd like**
/addbacklog or something similar and from there ask users for date and info related to entry
copy and move everything from the first row of date down one row
edit the first row

**Additional context**

**Comment by meganlee98** [comment]
### Suggestion:
/addbacklog feature
Similar flow to current /addentry, but add a date parameter to be defined before "type of entry"
### User flow:
1. User keys /addbacklog
2. User inputs date of trxn
3. User inputs "type of entry": Transport or Others
4. User inputs price
5. User inputs details (eg. "Bought a new shirt")
6. User inputs category
7. User inputs subcategory
8. User inputs mode of payment
9. Trxn logged

**Comment by brucewzj99** [comment]
released on v2.1.7
