### ISSUE TITLE
Bug in adding subcategories

### ISSUE THREAD

**Issue by meganlee98** [brucewzj99/tele-tracker-v2#25]
**Describe the bug**
Bug occurs when attempting to enter **7-11** as a sub-category.
Possibly other errors will occur if users try to add other sub-categories that only have numbers & special chars [-/:]

**To Reproduce**
1. Enter 7-11 into any of the sub-category cells
2. Google sheets automatically converts it to a date format
3. Category dropdown list shows up as (Category)-45237
<img width="116" alt="Screenshot 2023-08-17 at 4 01 10 PM" src="https://github.com/brucewzj99/tele-tracker-v2/assets/142468556/19a97148-5934-42b9-83b8-b50a5c20e458">

Possible fix: 

- [x] Format cells for all sub-categories to ensure all input is converted to plain text string?

**Comment by brucewzj99** [comment]
Formatted the template to plain string for the mention fields
