### ISSUE TITLE
bug when using /backlog

### ISSUE THREAD

**Issue by zairae** [brucewzj99/tele-tracker-v2#32]
**Describe the bug**
Error when trying to use the /backlog commands. Process managed to run through till the payment and category type but failed on logging transaction. This is probably because there is no transaction in the future.

E.g. Adding backlog for 14 January, but there is no transaction in the future (15 jan onwards), the bot cant find where is the last row of 14 January to add the new entry

Tap onto the row tracker by checking for the day tracker perhaps ?

**Comment by brucewzj99** [comment]
will prioritize this and try to push fix by end Feb

**Comment by brucewzj99** [comment]
fix in 2.2

**Comment by brucewzj99** [comment]
push new fix in 2.3.2
