### ISSUE TITLE
cant input transaction after reaching payment type 

### ISSUE THREAD

**Issue by angyuxi** [brucewzj99/tele-tracker-v2#42]
**Describe the bug**
input price, selected payment time (renamed to eg. credit card), when press credit card, it appear to have error and cannot be logged 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brucewzj99** [comment]
Hey @angyuxi , can you provide some screenshots in regard to this issue.

**Comment by angyuxi** [comment]
hi bruce
[image0.png]
Sent from my iPhone

On 3 May 2024, at 5:51 PM, Bruce Wang ***@***.***> wrote:

﻿

Hey @angyuxi<https://github.com/angyuxi> , can you provide some screenshots in regard to this issue.

**Comment by brucewzj99** [comment]
Hi @angyuxi, im not able to see the screenshot, could you email it to me at telefinance@brucewzj.com 

if not perhaps you want to try /cancel and retry adding the entry. Thanks
